#ifndef CLP_KEYCODES_H_
#define CLP_KEYCODES_H_

#include "Clip/Core/Core.h"

#ifdef CLP_PLATFORM_WINDOWS
#include <Windows.h>
#define CLP_MSE_LBUTTON				0x02
#define CLP_MSE_RBUTTON				0x08
#define CLP_MSE_MBUTTON				0x04
#define CLP_MSE_BUTTON1				CL_MSE_LBUTTON
#define CLP_MSE_BUTTON2				CL_MSE_RBUTTON
#define CLP_MSE_BUTTON3				CL_MSE_MBUTTON
#define CLP_MSE_BUTTON4				0x10
#define CLP_MSE_BUTTON5				0x20
#define CLP_KEY_BACKSPACE			VK_BACK
#define CLP_KEY_TAB					VK_TAB
#define CLP_KEY_ENTER				VK_RETURN
#define CLP_KEY_SHIFT				VK_SHIFT
#define CLP_KEY_CTRL					VK_CONTROL
#define CLP_KEY_ALT					VK_MENU
#define CLP_KEY_PAUSE				VK_PAUSE
#define CLP_KEY_CAPSLOCK				VK_CAPITAL
#define CLP_KEY_ESC					VK_ESCAPE
#define CLP_KEY_SPACE				VK_SPACE
#define CLP_KEY_PAGEUP				VK_PRIOR
#define CLP_KEY_PAGEDOWN				VK_NEXT
#define CLP_KEY_END					VK_END
#define CLP_KEY_HOME					VK_HOME
#define CLP_KEY_LEFT					VK_LEFT
#define CLP_KEY_RIGHT				VK_RIGHT
#define CLP_KEY_UP					VK_UP
#define CLP_KEY_DOWN					VK_DOWN
#define CLP_KEY_PRINTSCREEN			VK_SNAPSHOT
#define CLP_KEY_INSERT				VK_INSERT
#define CLP_KEY_DELETE				VK_DELETE
#define CLP_KEY_0					0x30
#define CLP_KEY_1					0x31
#define CLP_KEY_2					0x32
#define CLP_KEY_3					0x33
#define CLP_KEY_4					0x34
#define CLP_KEY_5					0x35
#define CLP_KEY_6					0x36
#define CLP_KEY_7					0x37
#define CLP_KEY_8					0x38
#define CLP_KEY_9					0x39
#define CLP_KEY_A					0x41
#define CLP_KEY_B					0x42
#define CLP_KEY_C					0x43
#define CLP_KEY_D					0x44
#define CLP_KEY_E					0x45
#define CLP_KEY_F					0x46
#define CLP_KEY_G					0x47
#define CLP_KEY_H					0x48
#define CLP_KEY_I					0x49
#define CLP_KEY_J					0x4a
#define CLP_KEY_K					0x4b
#define CLP_KEY_L					0x4c
#define CLP_KEY_M					0x4d
#define CLP_KEY_N					0x4e
#define CLP_KEY_O					0x4f
#define CLP_KEY_P					0x50
#define CLP_KEY_Q					0x51
#define CLP_KEY_R					0x52
#define	CLP_KEY_S					0x53
#define CLP_KEY_T					0x54
#define CLP_KEY_U					0x55
#define CLP_KEY_V					0x56
#define CLP_KEY_W					0x57
#define CLP_KEY_X					0x58
#define CLP_KEY_Y					0x59
#define CLP_KEY_Z					0x5a
#define CLP_KEY_NUMPAD0				VK_NUMPAD0
#define CLP_KEY_NUMPAD1				VK_NUMPAD1
#define CLP_KEY_NUMPAD2				VK_NUMPAD2
#define CLP_KEY_NUMPAD3				VK_NUMPAD3
#define CLP_KEY_NUMPAD4				VK_NUMPAD4
#define CLP_KEY_NUMPAD5				VK_NUMPAD5
#define CLP_KEY_NUMPAD6				VK_NUMPAD6
#define	CLP_KEY_NUMPAD7				VK_NUMPAD7
#define CLP_KEY_NUMPAD8				VK_NUMPAD8
#define CLP_KEY_NUMPAD9				VK_NUMPAD9
#define CLP_KEY_MULTIPLY				VK_MULTIPLY
#define CLP_KEY_ADD					VK_ADD
#define CLP_KEY_SEPARATOR			VK_SEPARATOR
#define CLP_KEY_SUBTRACT				VK_SUBTRACT
#define CLP_KEY_DECIMAL				VK_DECIMAL
#define CLP_KEY_DIVIDE				VK_DIVIDE
#define CLP_KEY_F1					VK_F1
#define CLP_KEY_F2					VK_F2
#define CLP_KEY_F3					VK_F3
#define CLP_KEY_F4					VK_F4
#define CLP_KEY_F5					VK_F5
#define CLP_KEY_F6					VK_F6
#define CLP_KEY_F7					VK_F7
#define CLP_KEY_F8					VK_F8
#define CLP_KEY_F9					VK_F9
#define CLP_KEY_F10					VK_F10
#define CLP_KEY_F11					VK_F11
#define CLP_KEY_F12					VK_F12
#define CLP_KEY_F13					VK_F13
#define CLP_KEY_F14					VK_F14
#define CLP_KEY_F15					VK_F15
#define CLP_KEY_F16					VK_F16
#define CLP_KEY_F17					VK_F17
#define CLP_KEY_F18					VK_F18
#define CLP_KEY_F19					VK_F19
#define CLP_KEY_F20					VK_F20
#define CLP_KEY_F21					VK_F21
#define CLP_KEY_F22					VK_F22
#define CLP_KEY_F23					VK_F23
#define CLP_KEY_F24					VK_F24
#define CLP_KEY_NUMLOCK				VK_NUMLOCK
#define CLP_KEY_SEMICOLON			VK_OEM_1
#define CLP_KEY_PLUS					VK_OEM_PLUS
#define CLP_KEY_COMMA				VK_OEM_COMMA
#define CLP_KEY_MINUS				VK_OEM_MINUS
#define CLP_KEY_PERIOD				VK_OEM_PERIOD
#define CLP_KEY_SLASH				VK_OEM_2
#define CLP_KEY_TILDA				VK_OEM_3
#define CLP_KEY_OPENBRACKET			VK_OEM_4
#define CLP_KEY_BACKSLASH			VK_OEM_5
#define CLP_KEY_CLOSEBRACKET			VK_OEM_6
#define CLP_KEY_QUOTE				VK_OEM_7
#elif defined( CLP_PLATFORM_LINUX )

#endif

#endif